Kalamconst/urls.py
from django.contrib import admin
from django.urls import path, include

# for register static path in urls.py
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path

from app import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),


    path("blog", views.blog, name="blog"),
    path('blog/<int:id>',views.blogview,name='blogview'),
    path('delblog/<int:id>',views.delblog,name='delblog'),
    # path("createpost", views.blog, name="blog"),
    path('blog_post/',views.blog_post, name='blog_post'),


    path('django',views.login_admin,name='django'),

    path('admin_home',views.admin_home,name='adminhome'),
    
    path('admins',views.admins,name='admins'),
    path('deladmins/<str:id>',views.deladmins,name='deladmins'),
    path('edit-admin/<str:id>',views.editadmin,name='editadmin'),

    path('employees',views.employees,name='employees'),
    path('delemployees/<str:id>',views.delemployees,name='delemployees'),
    # path('manageemployees',views.manage_emp,name='manage_emp'),



    path('emp_home',views.employee_home,name='emphome'),
    path('cus_home',views.customer_home,name='cushome'),

    
    path('projectcategories',views.projectcategories,name='projectcategories'),
    path('editprojectcategories/<str:pk>',views.editprojectcategories,name='editprojectcategories'),
    path('deleteprojectcategory/<int:id>',views.deleteprojectcategory,name='deleteprojectcategory'),


    path('locations',views.projectlocations,name='locations'),
    path('editlocations/<int:id>',views.editprojectlocations,name='editlocations'),
    path('dellocations/<int:id>',views.delprojectlocations,name='dellocations'),


    path("about", views.about, name="about"),
    path("services", views.services, name="services"),
    path("contact_us", views.contact_us, name="contactus"),
    # path('quotation',views.quotation, name='quotation'),
    
]

app/forms.py
#from fileinput import FileInput

from dataclasses import field
from statistics import quantiles
from django import forms

from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import *


class CustomUserForm(UserCreationForm):
    username=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter username'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'your@email.com','autocomplete':'off'}))
    first_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the first Name of user'}))
    last_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the last Name of user'}))
    password1=forms.Field(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Enter the New password'}))
    password2=forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Enter the password again'}))


class EmployeeProfileForm(CustomUserForm):
    emp_phon=forms.CharField(label='Employee Phone Number',max_length=13,widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter the Emplyee Phone Number'}))
    emp_address=forms.CharField(label='Employee Address', max_length=500,widget=forms.Textarea(attrs={'class':'form-control','rows':3}))
    profile_pic=forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control'}))
    add_to_about=forms.BooleanField(required= False)
    class Meta:
        model=Employee
        fields=(
                'username',
                'email',
                'first_name',
                'last_name',
                'password1',
                'password2',
                'emp_phon',
                'emp_address',
                'profile_pic',
                'add_to_about',
                )



class AdminProfileForm(CustomUserForm):          
    admin_phon=forms.CharField(label='Admin Phone Number',max_length=13,widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter the Admin Phone Number',}))
    admin_address=forms.CharField(label='Admin Address', max_length=500,widget=forms.Textarea(attrs={'class':'form-control','rows':3}))
    profile_pic=forms.FileField(widget=forms.FileInput(attrs={'class':'form-control'}))
    add_to_home=forms.BooleanField(required= False)
    add_to_about=forms.BooleanField(required= False)
    class Meta:
        model=Admin
        fields=(
                'username',
                'email',
                'first_name',
                'last_name',
                'password1',
                'password2',
                'admin_phon',
                'admin_address',
                'profile_pic',
                'add_to_home',
                'add_to_about',

                )


class BlogPostForm(forms.Form): #working
    title=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the title','name':'title'}))
    project=forms.ModelChoiceField(ProjectLocations.objects.filter(is_completed=False), label='Select Project and Location',widget=forms.Select(attrs={'class':'form-control'}))
    site_pic=forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control'}))
    updates=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','rows':3,'placeholder':'Enter the Points'}))

    class Meta:
        model=Blog
        fields=['title',
                'site_pic',
                'updates'
                ]
class ProjectCategoryForm(forms.Form):
    pname=forms.CharField(label='Project Name',max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the new project Name',}))
    ppic=forms.ImageField(label='Project Picture',widget=forms.FileInput(attrs={'class':'form-control'}))
    pdescription=forms.CharField(label='Project Descriptions', max_length=500,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Enter the short definition of your project','rows':'3'}))
    icon=forms.CharField(label='Paste icon code',max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'copy the from ICONs Code table which blow the Projects',}))
    add_home=forms.BooleanField(
                            label='Are you want to show this project on home page?',
                            widget=forms.RadioSelect(
                                choices=[
                                    (True, 'yes'),
                                    (False, 'No')
                                    ]
                                )
                            )

    class Meta:
        model=ProjectCategory
        fields=[
            'pname',
            'ppic',
            'pdescription',
            'icon',
            'add_home'

        ]

class EditProjectCategoryForm(forms.ModelForm):
    pname=forms.CharField(label='Project Name',max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the new project Name',}))
    ppic=forms.ImageField(label='Project Picture',widget=forms.FileInput(attrs={'class':'form-control'}))
    pdescription=forms.CharField(label='Project Descriptions', max_length=500,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Enter the short definition of your project','rows':'3'}))


    class Meta:
        model=ProjectCategory
        fields=[
            'pname',
            'ppic',
            'pdescription'

        ]


class ProjectLocationForm(forms.Form): #projectlocations
    # BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))
    location=forms.CharField(label='Project Location', max_length=150,widget=forms.TextInput(attrs={'class':'form-control','placeholer':'Enter the project Location'}))
    project=forms.ModelChoiceField(ProjectCategory.objects.all(),label='Select Project Type',widget=forms.Select(attrs={'class':'form-control'}))
    engineer=forms.ModelChoiceField(User.objects.filter(role="EMPLOYEE"),label='Assign Engineer',widget=forms.Select(attrs={'class':'form-control','rows':'3'}))
    site_pic=forms.ImageField(label='Project Picture',widget=forms.FileInput(attrs={'class':'form-control'}))
    is_completed=forms.BooleanField(
        required=False,
        label='This project is completed ?',
        widget=forms.RadioSelect(
            choices=[
                (True, 'Completed'),
                (False, 'Not yet')
                ]
            )
        )
    class Meta:
        model=ProjectLocations
        fields=(
            'location',
            'project',
            'engineer',
            'site_pic',
            'is_completed'
        )

# class QuotationForm(forms.Form):
#     name=forms.CharField(max_length=100, required=False)
#     email=forms.EmailField(required=False)
#     phone=forms.CharField(max_length=13, required=False)
#     service=forms.ModelChoiceField(ProjectCategory.objects.all(),required=False,widget=forms.Select(attrs={'class':'form-control'}))
#     note=forms.CharField(required=False,widget=forms.Textarea(attrs={'class':'form-control','rows':3,'placeholder':'Enter the Points'}))
#     class Meta:
#         model=Quotation
#         fields=(
#             'name',
#             'email',
#             'phone',
#             'service',
#             'note',

#         )

class CustomUserChangeForm(UserChangeForm):
    username=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control border-0','style':'height: 55px;'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','autocomplete':'off'}))
    first_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name=forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))


    class Meta:
        model=User
        fields=(
            'username',
            'email',
            'first_name',
            'last_name',
        )

templates/users/admin/admin_home.html
{% extends 'base/pageheader.html' %}


    {% block title %}Admin {% endblock title %}
    {% block page_header %} Welcome back..! {{ user.username }}{% endblock page_header %}
    {% block page_header_name %} blogger{% endblock page_header_name %}

    {% block content3 %}
    {% include 'base/msg.html' %}

    {% endblock content3 %}



{% block content2 %}
{% if user.role == 'ADMIN' %}


    {% block content4 %}

<div class="row justify-content-center align-items-center g-2">
    <div class="col">Column</div>
    <div class="col">
        <a name="" id="" class="btn btn-primary" href="{% url 'editadmin' user.id %}" role="button">Edit personal details</a>
    </div>
    <div class="col">Column</div>
</div>



            <div class="table-responsive">
                <h1 class="text-center">Service requests</h1>
                <table class="table table-striped
                table-hover	
                table-borderless
                table-dark
                align-middle">
                    <thead class="table-light">
                        <caption>No more pending requests</caption>
                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Service</th>
                            <th scope="col">Name & Phone</th>
                            <th scope="col">email & Date</th>
                            <th scope="col">Message</th>
                            
                        </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for i in data %}
                                {% if i.response == False %}
                                    <tr class="table-primary" >
                                        <td scope="row">{{ forloop.counter }}</td>
                                        
                                        <td>{{ i.service }}</td>
                                        <td>{{ i.name }}<br>{{ i.phone }}</td>
                                        <td>{% if i.email %}
                                                {{ i.email }}
                                            {% else %}
                                                <i class="text-secondary">Email Not Provided</i>
                                            {% endif %}
                                                <br>{{ i.created_at }}</td>

                                        <td>{% if i.note %}
                                                    {{ i.note }}
                                                {% else %}
                                                    <i class="text-secondary">Message Not Provided</i>
                                                {% endif %}</td>
                                    </tr>
                                     
                                {% endif %} 
                                   
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            
                        </tfoot>
                </table>
            </div>
            

    {% endblock content4 %}


{% else %}
<!-- 404 Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <i class="bi bi-exclamation-triangle display-1 text-primary"></i>
                <h1 class="display-1">404</h1>
                <h1 class="mb-4">Page Not Found</h1>
                <p class="mb-4">We’re sorry, the page you have looked for does not exist in our website! Maybe go to our home page or login with admin credencials ?</p>
                <a class="btn btn-primary rounded-pill py-3 px-5" href="{% url 'home' %}">Go Back To Home</a> or
                <a class="btn btn-info rounded-pill text-white py-3 px-5" href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </div>
</div>
<!-- 404 End -->
{% endif %}


{% endblock content2 %}

templates/users/admin/admins.html
{% extends 'users/admin/admin_home.html' %}
{% load static %}
{% block content4 %}


  <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enter New Admin Details here</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action='{% url 'admins' %}' enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <p>{{ data3.username.label_tag }} {{ data3.username }}</p>
                            <p>{{ data3.email.label_tag }} {{ data3.email }}</p>
                            <p>{{ data3.first_name.label_tag }} {{ data3.first_name }}</p>
                            <p>{{ data3.last_name.label_tag }} {{ data3.last_name }}</p>
                            <p>{{ data3.password1.label_tag }} {{ data3.password1 }}</p>
                            

                        </div>
                        <div class="col-6">
                            <p>{{ data3.password2.label_tag }} {{ data3.password2 }}</p>
                            <p>{{ data3.admin_phon.label_tag }} {{ data3.admin_phon }}</p>
                            <p>{{ data3.admin_address.label_tag }} {{ data3.admin_address }}</p>
                            <p>{{ data3.profile_pic.label_tag }} {{ data3.profile_pic }}</p>
                            
                            <div class="row justify-content-center align-items-center g-2">
                                <div class="col"><p>{{ data3.add_to_about.label_tag }} {{ data3.add_to_about }}</p></div>
                                <div class="col"> <p>{{ data3.add_to_home.label_tag }} {{ data3.add_to_home }}</p></div>
                            </div> 
                            {% comment %} 
                            <img class="img-fluid" src="{% static 'asserts/img/3x4image.jpg' %}" alt="3:4">
                             {% endcomment %}
                        </div>
                        
                           
                    </div>
                    <div class="row my-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>




<!-- Team Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
            <h6 class="text-primary">Team Member</h6>
            
            
              
            <h1 class="mb-4">Experienced Team Admins</h1><!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add new Admin
            </button>
        </div>
        <div class="row g-4">
            {% for i in data %}

            <div class="col-lg-4 col-md-6 mx-auto wow fadeInUp" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="team-item rounded overflow-hidden">
                    <div class="d-flex">
                        <img class="img-fluid w-75" src="{{ i.profile_pic.url }}" onerror="this.onerror=null;this.src='{% static 'asserts/img/admin_user.jpg' %}';" alt="admin profile picture">                    
                        <div class="team-social w-25">
                            <a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i class="fab fa-instagram"></i></a>
                            <a class="btn btn-lg-square btn-outline-primary rounded-circle mt-3" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-lg-square btn-outline-info rounded-circle mt-3" href="{% url 'editadmin'  i.user.id %}"><i class="bi bi-pencil"></i></a>
                            <a class="btn btn-lg-square btn-outline-danger rounded-circle mt-3" href="{% url 'deladmins' i.user.id %}" onclick="return confirm('Are you surly want to remove {{ i.user.username }}' )"><i class="fa fa-trash"></i></a>
                            
                           
                        </div>
                    </div>
                    <div class="p-4">
                        <h5>{{ i.user.first_name }} {{i.user.last_name }} - <span>{{ i.user.username }}</span></h5>
                        <span>Designation : xyz</span><br>
                        <span>Phone Number : {{ i.admin_phon }}</span>
                        <pre>Address :{{ i.admin_address }}</pre>
                        <div class="row justify-content-center align-items-center g-2">
                            <div class="col">
                                {% if i.add_to_home %}
                                    <p><i class="fa fa-check-circle text-primary me-3"></i>Home page</p>
                                {% else %}
                                    <p><i class="bi bi-x-circle-fill text-danger me-3"></i>Home page</p>
                                {% endif %}
                            </div>
                            <div class="col">
                                {% if i.add_to_about %}
                                <p><i class="fa fa-check-circle text-primary me-3"></i>About page</p>
                                {% else %}
                                    <p><i class="bi bi-x-circle-fill text-danger me-3"></i>About page</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Team End -->
<hr>
<div class="row justify-content-center align-items-center g-2">
    <h5 class="h5 text-center">**important**</h5>
    <div class="col-1"></div>
    <div class="col-3">
        <img class="img-fluid" src="{% static 'asserts/img/3x4image.jpg' %}" alt="3:4">
    </div>
    <div class="col-6">
        <p> &nbsp;* 'While uploading <b>Proile pictures</b> please make sure your picture should be is <b>3:4</b> in portrait.
            <br>&nbsp;* If not please crop it for better viewing Experience...</p>
            <p class="text-center"> Thank you !! </p>
    </div> 
    <div class="col-2"></div>
</div>




<script>
    const nodes = document.querySelectorAll('.amt');
    const arr = Array.from(nodes);
    const res = arr.reduce((acc,curr) => {
        return acc += Number(curr.textContent)
    }, 0);
    document.getElementById("net").innerHTML="Rs : "+res;
</script>

    
</div>{% endblock content4 %}

templates/users/admin/editadmin.html
{% extends 'users/admin/admin_home.html' %}
{% load static %}
{% block content4 %}


<p class="text-danger"> This page under development stage currently not working<p>

<div class="row justify-content-center align-items-center g-2">
    
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col">{{ d2 }}</div>
        <button class="btn btn-primary rounded-pill py-3 px-5" type="submit">Update</button>
    </form>
</div>




<div class="container-fluid bg-light overflow-hidden px-lg-0" style="margin: 6rem 0;">
    <div class="container contact px-lg-0">
        <div class="row g-0 mx-lg-0">
            <div class="col-lg-8 contact-text py-5 wow fadeIn" data-wow-delay="0.5s">
                <div class="p-lg-5 ps-lg-0">
                    <h6 class="text-primary">{{ d1.user.username }}</h6>
                    <h1 class="mb-4">Edit your Profile Details</h1>
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-12 col-sm-6">
                                <label for="id_username">Username:</label>
                                <input type="text" name="username" class="form-control border-0" required maxlength="100" style="height: 55px;" value="{{ d1.user.username }}" id="id_username">
                            </div>
                            <div class="col-12 col-sm-6">
                                <p>{{ d2.username.label_tag }} {{ d2.username }}</p>
                            </div>
                            <div class="col-12 col-sm-6">
                                <label for="id_email">Email:</label>
                                <input type="email" class="form-control border-0" required style="height: 55px;" name="email" value="{{ d1.user.email }}" id="id_email">
                            </div>
                            <div class="col-12 col-sm-6">
                                <label for="id_first_name">First name:</label>
                                <input type="text" class="form-control border-0" required style="height: 55px;" name="first_name" value="{{ d1.user.first_name }}" id="id_first_name">
                            </div>
                            <div class="col-12 col-sm-6">
                                <label for="id_last_name">Last name:</label>
                                <input type="text" class="form-control border-0" required style="height: 55px;" name="last_name" value="{{ d1.user.last_name }}" id="id_last_name">
                            </div>
                            <div class="col-12 col-sm-6">
                                <label for="id_admin_phon">Phone Number:</label> 
                                <input type="text" class="form-control border-0" required style="height: 55px;" name="admin_phon" value="{{ d1.admin_phon }}" id="id_admin_phon">
                            </div>
                            <div class="col-12 col-sm-6">
                                <label for="id_profile_pic">Profile pic:</label>
                                <input type="file" class="form-control border-1" style="height: 55px;" name="profile_pic" id="id_profile_pic">
                            </div>

                            <div class="col-12">
                                <label for="id_admin_address">Address:</label>
                                <textarea class="form-control border-0" required name="admin_address" maxlength="500" style="height: 100px" id="id_admin_address">{{ d1.admin_address }}</textarea>
                            </div>
                            <div class="row justify-content-center align-items-center g-2">
                                <div class="col form-check"> 
                                    <p>
                                        <label for="id_add_to_home" class="form-check-label">Add to home</label> 
                                        <input type="checkbox" class="form-check-input" name="add_to_home" {% if d1.add_to_home %}checked{% endif %} id="add_to_home">
                                    </p>
                                </div>
                                <div class="col form-check">
                                    <p>
                                        <label for="id_add_to_about" class="form-check-label">Add to about</label>
                                        <input type="checkbox" class="form-check-input" name="add_to_about" {% if d1.add_to_about %} checked {% endif %} id="add_to_about">
                                    </p>
                                </div>
                                
                            </div> 
                            <div class="col-12">
                                <button class="btn btn-primary rounded-pill py-3 px-5" type="submit">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 py-5 pe-lg-0 wow fadeIn" data-wow-delay="0.5s"style="min-height: 400px;">
                <div class="position-relative h-100">
                    <div class="team-item rounded overflow-hidden w-75">
                        <div class="d-flex">
                            <img class="img-fluid" src="{{ d1.profile_pic.url }}" onerror="this.onerror=null;this.src='{% static 'asserts/img/admin_user.jpg' %}';" alt="">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content4 %}

templates/users/admin/editprojects.html
{% extends 'users/admin/admin_home.html' %}
{% load static %}
{% block content4 %}



<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
              <label for="" class="form-label">Project Name</label>
              <input type="text" required name="pname" id="pname" class="form-control" value="{{ d1.pname }}" maxlength="100">
              
            </div>
            <div class="mb-3">
                {% if d1.ppic %}
                    <img class="img-thumbnail" src="{{ d1.ppic.url }}" alt="{{ d1.pname }} picture">
                {% endif %}
            
              <label for="" class="form-label"></label>
              <input type="file" class="form-control" name="ppic" id="ppic">
            </div>
            <div class="mb-3">
              <label for="" class="form-label"></label>
              <textarea required name="pdescription" cols="40" rows="3" class="form-control" maxlength="500" id="id_pdescription">{{ d1.pdescription}}</textarea>
                
              
            </div>
            <div class="row my-3">
                <button type="submit" class="btn btn-primary">Update</button>
            </div> 
        </div>
          
    </div>
    
</form>

{% endblock content4 %}